### ISSUE TITLE
GitPad expecting crazy cygdrive paths?

### ISSUE THREAD

**Issue by BrainSlugs83** [github/GitPad#21]
When I try to use "git commit" after installing, I get the following exception:

    System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\cygdrive\c\Projects\[ProjectName]\.git\COMMIT_EDITMSG'.
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
       at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
       at System.IO.StreamReader..ctor(String path, Encoding encoding)
       at System.IO.File.ReadAllText(String path, Encoding encoding)
       at Gitpad.Program.Main(String[] args)

When I press CTRL+C (it just sits there locked), I get the following two lines of text:
    error: There was a problem with the editor '~/AppData/Roaming/GitPad/GitPad.exe'.
    Please supply the message using either -m or -F option.

Note, the repository I'm using (and current directory in the command prompt session) is "C:\Projects\[ProjectName]" (no brackets on the actual project name).

**Comment by shiftkey** [comment]
What version of Git are you running?

**Comment by BrainSlugs83** [comment]
This was my bad -- apparently cygwin\bin was in my path and I was using that version of Git outside of bash.  Total PEBCAK.

**Comment by shiftkey** [comment]
@BrainSlugs83 no problem, thanks for confirming!
